"""Initial migration with MVP models

Revision ID: 883e7bc4375b
Revises:
Create Date: 2025-12-01 01:36:25.277699

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '883e7bc4375b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retailer_prices',
    sa.Column('material_name', sa.Text(), nullable=False),
    sa.Column('material_category', sa.Text(), nullable=False),
    sa.Column('retailer_name', sa.String(length=50), nullable=False),
    sa.Column('product_sku', sa.Text(), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_of_measure', sa.Text(), nullable=False),
    sa.Column('availability_status', sa.String(length=20), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_prices_last_updated'), 'retailer_prices', ['last_updated'], unique=False)
    op.create_index(op.f('ix_retailer_prices_material_category'), 'retailer_prices', ['material_category'], unique=False)
    op.create_index(op.f('ix_retailer_prices_material_name'), 'retailer_prices', ['material_name'], unique=False)
    op.create_index(op.f('ix_retailer_prices_retailer_name'), 'retailer_prices', ['retailer_name'], unique=False)
    op.create_table('user_profiles',
    sa.Column('skill_level', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('project_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_actual_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.Text(), nullable=True),
    sa.Column('stripe_customer_id', sa.Text(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('project_photos',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('cv_analysis_status', sa.String(length=20), nullable=False),
    sa.Column('cv_analysis_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cv_confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_photos_cv_analysis_status'), 'project_photos', ['cv_analysis_status'], unique=False)
    op.create_index(op.f('ix_project_photos_project_id'), 'project_photos', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_photos_scan_status'), 'project_photos', ['scan_status'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('total_estimated_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('shopping_list_items',
    sa.Column('shopping_list_id', sa.UUID(), nullable=False),
    sa.Column('material_name', sa.Text(), nullable=False),
    sa.Column('material_category', sa.String(length=20), nullable=False),
    sa.Column('calculated_quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('waste_factor_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('actual_purchase_quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('estimated_unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_list_items_material_category'), 'shopping_list_items', ['material_category'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_purchase_status'), 'shopping_list_items', ['purchase_status'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_shopping_list_id'), 'shopping_list_items', ['shopping_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_list_items_shopping_list_id'), table_name='shopping_list_items')
    op.drop_index(op.f('ix_shopping_list_items_purchase_status'), table_name='shopping_list_items')
    op.drop_index(op.f('ix_shopping_list_items_material_category'), table_name='shopping_list_items')
    op.drop_table('shopping_list_items')
    op.drop_table('shopping_lists')
    op.drop_index(op.f('ix_project_photos_scan_status'), table_name='project_photos')
    op.drop_index(op.f('ix_project_photos_project_id'), table_name='project_photos')
    op.drop_index(op.f('ix_project_photos_cv_analysis_status'), table_name='project_photos')
    op.drop_table('project_photos')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_retailer_prices_retailer_name'), table_name='retailer_prices')
    op.drop_index(op.f('ix_retailer_prices_material_name'), table_name='retailer_prices')
    op.drop_index(op.f('ix_retailer_prices_material_category'), table_name='retailer_prices')
    op.drop_index(op.f('ix_retailer_prices_last_updated'), table_name='retailer_prices')
    op.drop_table('retailer_prices')
    # ### end Alembic commands ###
